var notebook = {
	title: 'TOEFL Advanced 1162',
	list: [
		{word: "abacus", definition: "frame with balls for calculating"},
		{word: "abate", definition: "to lessen to subside"},
		{word: "abdication", definition: "giving up control authority"},
		{word: "aberration", definition: "straying away from what is normal"},
		{word: "abet", definition: "help/encourage smb (in doing wrong)"},
		{word: "abeyance", definition: "suspended action"},
		{word: "abhor", definition: "to hate to detest"},
		{word: "abide", definition: "be faithful to endure"},
		{word: "abjure", definition: "promise or swear to give up"},
		{word: "abraded", definition: "rubbed off worn away by friction"},
		{word: "abrogate", definition: "repeal or annul by authority"},
		{word: "abscond", definition: "to go away suddenly (to avoid arrest)"},
		{word: "abstruse", definition: "difficult to comprehend obscure"},
		{word: "abut", definition: "border on"},
		{word: "abysmal", definition: "bottomless extreme"},
		{word: "acarpous", definition: "effete no longer fertile worn out"},
		{word: "acclaimed", definition: "welcomed with shouts and approval"},
		{word: "accolade", definition: "praise approval"},
		{word: "accretion", definition: "the growing of separate things into one"},
		{word: "adamant", definition: "kind of stone inflexible"},
		{word: "admonitory", definition: "containing warning"},
		{word: "adorn", definition: "add beauty decorate"},
		{word: "adulteration", definition: "making unpure poorer in quality"},
		{word: "affable", definition: "polite and friendly"},
		{word: "affinity", definition: "close connection relationship"},
		{word: "aggravate", definition: "make worse irritate"},
		{word: "agile", definition: "active quick-moving"},
		{word: "agog", definition: "eager/excited"},
		{word: "ail", definition: "trouble be ill"},
		{word: "alacrity", definition: "eager and cheerful readiness"},
		{word: "alcove", definition: "recess/partially enclosed place"},
		{word: "allegiance", definition: "duty support loyalty"},
		{word: "alleviate", definition: "make (pain) easier to bear"},
		{word: "alloy", definition: "to debase by mixing with something inferior"},
		{word: "aloof", definition: "reserved indifferent"},
		{word: "amalgamate", definition: "mix combine unite societies"},
		{word: "ambidextrous", definition: "able to use the left hand or the right equally well"},
		{word: "ambiguous", definition: "doubtful uncertain"},
		{word: "ambivalent", definition: "having both of two contrary meanings"},
		{word: "ameliorate", definition: "improve make better"},
		{word: "amortize", definition: "end (a debt) by setting aside money"},
		{word: "anguish", definition: "severe suffering"},
		{word: "animosity", definition: "strong dislike"},
		{word: "antidote", definition: "medicine used against a poison or a disease"},
		{word: "antithetical", definition: "direct opposing"},
		{word: "apartheid", definition: "brutal racial discrimination"},
		{word: "aplomb", definition: "self-confidence"},
		{word: "apostate", definition: "one who abandons long-held religious or political convictions"},
		{word: "apotheosis", definition: "deification glorification to godliness"},
		{word: "appease", definition: "make quiet or calm"},
		{word: "apprehensive", definition: "grasping understanding fear unhappy feeling about future"},
		{word: "apprise", definition: "give notice to inform"},
		{word: "approbation", definition: "approval"},
		{word: "apropos", definition: "appropriate to the situation apt"},
		{word: "apt", definition: "well-suited quick-witted"},
		{word: "arabesque", definition: "a complex ornate design"},
		{word: "arboreal", definition: "of connected with trees"},
		{word: "ardor", definition: "enthusiasm"},
		{word: "arduous", definition: "steep difficult ascent laborious"},
		{word: "argot", definition: "jargon slang"},
		{word: "arrant", definition: "in the highest degree"},
		{word: "arrogance", definition: "proud superior manner of behaviour"},
		{word: "articulate", definition: "speak distinctly connect by joints"},
		{word: "ascend", definition: "go or come up"},
		{word: "ascertain", definition: "get to know"},
		{word: "ascetic", definition: "practicing self-denial austere stark"},
		{word: "ascribe", definition: "consider to be the origin of or belonging to"},
		{word: "aseptic", definition: "surgically clean"},
		{word: "asperity", definition: "roughness harshness ill temper irritability"},
		{word: "aspersion", definition: "slander"},
		{word: "assail", definition: "with attack violently"},
		{word: "assiduous", definition: "diligent hard-working sedulous"},
		{word: "assuage", definition: "make smth (pain desire) less"},
		{word: "asterisk", definition: "the mark * (e.g.. omitted letters)"},
		{word: "astringent", definition: "substance that shrinks"},
		{word: "astute", definition: "clever quick at seeing to get an advantage"},
		{word: "atonement", definition: "repayment death of Jesus"},
		{word: "attenuate", definition: "make thin. weaken enervate"},
		{word: "attune", definition: "bring into harmony"},
		{word: "audacious", definition: "daring foolishly bold impudent"},
		{word: "augury", definition: "omen sign"},
		{word: "august", definition: "majestic venerable"},
		{word: "auspicious", definition: "favorable successful prosperous"},
		{word: "austere", definition: "severely moral and strict simple and plain"},
		{word: "auxiliary", definition: "helping supporting"},
		{word: "aver", definition: "affirm assert prove justify"},
		{word: "aversion", definition: "strong dislike"},
		{word: "avid", definition: "eager greedy"},
		{word: "avow", definition: "admit. Declare openly"},
		{word: "baleful", definition: "harmful ominous causing evil"},
		{word: "balk", definition: "obstacle purposely to get on the way of"},
		{word: "baneful", definition: "causing harm or ruin pernicious destructive"},
		{word: "barrage", definition: "artificial obstacle built across a river"},
		{word: "barren", definition: "not good enough unable to have young ones without value"},
		{word: "bask", definition: "in enjoy warmth and light"},
		{word: "beatify", definition: "to bless make happy or ascribe a virtue to"},
		{word: "bedizen", definition: "to adorn especially in a cheap showy manner"},
		{word: "belabor", definition: "beat hard"},
		{word: "bellicose", definition: "belligerent pugnacious warlike"},
		{word: "belligerent", definition: "(person nation) waging war"},
		{word: "benefactor", definition: "person who has given help"},
		{word: "benevolence", definition: "wish or activity in doing good"},
		{word: "benign", definition: "kind and gentle mild (climate)"},
		{word: "bequest", definition: "arrangement to give smth at death"},
		{word: "berate", definition: "scold sharply"},
		{word: "bereft", definition: "rob or dispossess of smth (material)"},
		{word: "bewilder", definition: "puzzle confuse"},
		{word: "bigot", definition: "stubborn narrow-minded person"},
		{word: "bilge", definition: "bulge the protuberance of a cask"},
		{word: "blandishment", definition: "flattery coaxing"},
		{word: "blandness", definition: "polite manner comforting uninteresting"},
		{word: "blatant", definition: "noisy and rough"},
		{word: "blithe", definition: "cheerful casual carefree"},
		{word: "bogus", definition: "sham counterfeit not genuine"},
		{word: "boisterous", definition: "loud noisy rough lacking restraint"},
		{word: "bolster", definition: "give greatly needed support"},
		{word: "boorish", definition: "crude offensive rude"},
		{word: "brash", definition: "hasty rush cheeky saucy"},
		{word: "brass", definition: "yellow metal (mixing copper and zinc)"},
		{word: "brazen", definition: "made of brass"},
		{word: "breach", definition: "opening broken place breaking"},
		{word: "brittle", definition: "easily broken"},
		{word: "broach", definition: "bring up announce begin to talk about"},
		{word: "brook", definition: "to tolerate endure"},
		{word: "buoyant", definition: "able to float light-hearted"},
		{word: "burgeon", definition: "grow forth send out buds"},
		{word: "burnish", definition: "to polish rub to a shine"},
		{word: "cabal", definition: "a scheme or plot a group of plotters"},
		{word: "cadge", definition: "to beg to get by begging"},
		{word: "cajole", definition: "use flattery or deceit to persuade"},
		{word: "calipers", definition: "metal supports attached to the legs measuring instrument"},
		{word: "calumny", definition: "slander aspersion"},
		{word: "candid", definition: "frank straight-forward"},
		{word: "cant", definition: "insincere talk/jargon"},
		{word: "cantankerous", definition: "bad-tempered/quarrelsome"},
		{word: "canvass", definition: "discuss thoroughly sort of touting"},
		{word: "castigate", definition: "to chastise correct by punishing"},
		{word: "castigation", definition: "severe punishment"},
		{word: "catalyst", definition: "substance that causes speeding up"},
		{word: "caustic", definition: "biting sarcastic"},
		{word: "censure", definition: "expression of blame or disapproval a rebuke"},
		{word: "centurion", definition: "leader of a unit of 100 soldiers"},
		{word: "chary", definition: "cautious wary"},
		{word: "chastened", definition: "corrected punished"},
		{word: "chastisement", definition: "punishment"},
		{word: "chauvinist", definition: "a blindly devoted patriot"},
		{word: "chicanery", definition: "legal trickery/false argument"},
		{word: "chisel", definition: "steel tool for shaping materials"},
		{word: "churl", definition: "bad-tempered person"},
		{word: "clamor", definition: "shout complain with a lot of noise"},
		{word: "clientele", definition: "customers"},
		{word: "clinch", definition: "come to grips/settle conclusively"},
		{word: "cling", definition: "to resist separation"},
		{word: "clot", definition: "half-solid lump formed from liquid"},
		{word: "cloture", definition: "closing device (in Parliament) to end a debate by voting"},
		{word: "coagulation", definition: "change to a thick and solid state"},
		{word: "coalescing", definition: "coming together and uniting into one substance"},
		{word: "coax", definition: "get smb to do smth by kindness"},
		{word: "coda", definition: "passage that completes a piece of music"},
		{word: "coddle", definition: "treat with care and tenderness"},
		{word: "coerce", definition: "compel to force to make obedient"},
		{word: "coeval", definition: "of the same period coexisting"},
		{word: "cogent", definition: "strong convincing"},
		{word: "cogitate", definition: "think deeply mediate"},
		{word: "cognizant", definition: "being fully aware of"},
		{word: "colander", definition: "bowl-shaped vessel with many holes used to drain off water"},
		{word: "collusion", definition: "secret agreement for a deceitful purpose"},
		{word: "combustion", definition: "process of burning"},
		{word: "commemorate", definition: "keep the memory of"},
		{word: "commodious", definition: "having plenty of space for what is needed"},
		{word: "commuter", definition: "person who travels regularly"},
		{word: "complaisance", definition: "tending to comply obliging willingness to please"},
		{word: "compunction", definition: "feeling of regret for one's action"},
		{word: "conceal", definition: "hide keep secret"},
		{word: "conceit", definition: "over-high opinion of too much pride"},
		{word: "conciliatory", definition: "reconciling soothing comforting mollifying"},
		{word: "concord", definition: "agreement or harmony"},
		{word: "concur", definition: "agree in opinion happen together"},
		{word: "condense", definition: "increase in density strength make laconic"},
		{word: "condone", definition: "forgive"},
		{word: "congeal", definition: "make or become stiff and solid"},
		{word: "conjoin", definition: "to join together"},
		{word: "connoisseur", definition: "a person with good judgement (e.g.. in art)"},
		{word: "connotation", definition: "suggestion in addition to"},
		{word: "consequential", definition: "pompous self important"},
		{word: "console", definition: "give comfort or sympathy to"},
		{word: "conspicuous", definition: "easily seen remarkable"},
		{word: "consternation", definition: "surprise and fear dismay"},
		{word: "constrain", definition: "compel"},
		{word: "constrict", definition: "make tight or smaller"},
		{word: "consume", definition: "get to the end of"},
		{word: "consummate", definition: "perfect/make perfect/complete"},
		{word: "contemn", definition: "to scorn or despise"},
		{word: "contentious", definition: "argumentative pugnacious combative quarrelsome"},
		{word: "contiguous", definition: "touching neighboring near"},
		{word: "contrite", definition: "filled with deep sorrow for wrongdoing"},
		{word: "contumacious", definition: "insubordinate rebellious"},
		{word: "conundrum", definition: "a riddle dilemma enigma"},
		{word: "conviction", definition: "convincing firm belief"},
		{word: "convoke", definition: "call together summon"},
		{word: "convoluted", definition: "complicated coiled twisted"},
		{word: "cordial", definition: "warm and sincere"},
		{word: "cordon", definition: "line (of police acting as a guard)"},
		{word: "cornucopia", definition: "abundant supply"},
		{word: "corporeal", definition: "physical of or for the body"},
		{word: "correlate", definition: "have a mutual relation"},
		{word: "corroboration", definition: "additional strengthening evidence"},
		{word: "countenance", definition: "to favor or approve of"},
		{word: "counterfeit", definition: "forgery"},
		{word: "countervail", definition: "counterbalance"},
		{word: "covert", definition: "disguised"},
		{word: "covetous", definition: "eagerly desirous"},
		{word: "cower", definition: "crouch shrink back"},
		{word: "coy", definition: "shy/modest (esp of a girl)"},
		{word: "crass", definition: "very great (es. stupidity)"},
		{word: "cravat", definition: "piece of linen worn as a necktie"},
		{word: "craven", definition: "cowardly"},
		{word: "crease", definition: "line made by crushing white line on the ground in cricket"},
		{word: "credulity", definition: "too great a readiness to believe things"},
		{word: "credulous", definition: "ready to believe things"},
		{word: "crush", definition: "press lose shape subdue overwhelm"},
		{word: "cryptic", definition: "secret with a hidden meaning"},
		{word: "cumbersome", definition: "burdensome heavy and awkward to carry"},
		{word: "curmudgeon", definition: "bad-tempered person"},
		{word: "curriculum", definition: "course of study"},
		{word: "cursory", definition: "quick hurried"},
		{word: "curtail", definition: "make shorter then was planned"},
		{word: "dainty", definition: "pretty/delicate(food)/difficult to please"},
		{word: "daunt", definition: "intimidate make fearful"},
		{word: "dawdler", definition: "person who is slow waste of time"},
		{word: "dearth", definition: "shortage"},
		{word: "debacle", definition: "a breakup overthrow sudden disaster"},
		{word: "decorum", definition: "propriety properness"},
		{word: "decree", definition: "order given by authority"},
		{word: "decry", definition: "disapprove of"},
		{word: "defer", definition: "postpone give way (to show respect)"},
		{word: "deferential", definition: "showing respect"},
		{word: "defiance", definition: "open disobedience or resistance"},
		{word: "delineate", definition: "to portray depict sketch out"},
		{word: "deluge", definition: "great flood heavy rush of water"},
		{word: "demagogue", definition: "person appealing not to reasons"},
		{word: "demur", definition: "to hesitate raise objections"},
		{word: "denigrate", definition: "blacken belittle sully defame"},
		{word: "denouement", definition: "an outcome or solution the unraveling of a plot"},
		{word: "deplete", definition: "use until none remains"},
		{word: "deposition", definition: "dethronement depositing"},
		{word: "deprave", definition: "make morally bad corrupt"},
		{word: "deprecate", definition: "protest against express disapproval of"},
		{word: "dereliction", definition: "deserting and leaving to fall into ruins"},
		{word: "derision", definition: "ridicule mockery deriding"},
		{word: "derivative", definition: "unoriginal obtained from another source"},
		{word: "derogatory", definition: "insulting tending to damage"},
		{word: "descry", definition: "catch sight of see smth in the distance"},
		{word: "desiccant", definition: "substance used to absorb moisture"},
		{word: "desuetude", definition: "cessation of use disuse"},
		{word: "desultory", definition: "aimless haphazard digressing at random"},
		{word: "deter", definition: "discourage hinder"},
		{word: "detraction", definition: "slandering verbal attack aspersion"},
		{word: "detumescence", definition: "diminishing or lessening of swelling"},
		{word: "deviance", definition: "being different in moral standards (from normal)"},
		{word: "dexterity", definition: "skill (esp. in handling)"},
		{word: "diaphanous", definition: "transparent gauzy"},
		{word: "diatribe", definition: "bitter and violent attack in words"},
		{word: "diffidence", definition: "shyness"},
		{word: "dilate", definition: "speak comprehensively become wider large"},
		{word: "disallow", definition: "refuse to allow or accept as a correct"},
		{word: "discern", definition: "see with an effort but clearly"},
		{word: "discomfit", definition: "confuse embarrass"},
		{word: "disconcert", definition: "upset the self-possession of"},
		{word: "discountenance", definition: "refuse to approve of"},
		{word: "discourse", definition: "speech lecture"},
		{word: "discredit", definition: "refuse to believe"},
		{word: "discreet", definition: "careful/prudent"},
		{word: "discrete", definition: "individually distinct"},
		{word: "disdain", definition: "look on with contempt"},
		{word: "disencumber", definition: "free from encumbrance"},
		{word: "disheveled", definition: "untidy"},
		{word: "disingenuous", definition: "sophisticated artful trying to deceive cunning"},
		{word: "disinter", definition: "dig up from the earth"},
		{word: "dislodge", definition: "move force from the place occupied"},
		{word: "dismal", definition: "sad gloomy miserable"},
		{word: "disparate", definition: "essentially different"},
		{word: "disproof", definition: "proof to the contrary"},
		{word: "dissemble", definition: "speak or behave so as to hide smth (in mind)"},
		{word: "disseminate", definition: "distribute (esp. ideas)"},
		{word: "dissent", definition: "have a different opinion refuse to assent"},
		{word: "dissolution", definition: "disintegration looseness in morals"},
		{word: "distraught", definition: "distracted violently upset in mind"},
		{word: "divergence", definition: "getting farther apart from a point"},
		{word: "divestiture", definition: "taking off getting rid of giving up"},
		{word: "divulge", definition: "make known smth secret"},
		{word: "doggerel", definition: "trivial poorly constructed verse"},
		{word: "dogmatic", definition: "positive certain arbitrary without room for discussion"},
		{word: "dolt", definition: "stupid fellow"},
		{word: "dormant", definition: "in a state of inactivity but awaiting development"},
		{word: "dote", definition: "show much fondness center one's attention"},
		{word: "drawl", definition: "slow way of speaking"},
		{word: "droll", definition: "jesting"},
		{word: "drone", definition: "male bee person who isn't self-employed"},
		{word: "drowsiness", definition: "feeling sleepy half asleep"},
		{word: "dubious", definition: "feeling doubt"},
		{word: "dud", definition: "no use person smth that fails"},
		{word: "dulcet", definition: "melodious harmonious"},
		{word: "dupe", definition: "cheat make a fool of"},
		{word: "duplicity", definition: "deliberate deception"},
		{word: "duress", definition: "threats to compel smb"},
		{word: "dwarf", definition: "person or smb much below the usual size"},
		{word: "dynamo", definition: "a generator something that produces electric current"},
		{word: "earthenware", definition: "dishes made of baked clay"},
		{word: "ebullience", definition: "exuberance outburst of feeling"},
		{word: "ebullient", definition: "overflowing with enthusiasm showing excitement"},
		{word: "ecumenical", definition: "representing the whole Christian world"},
		{word: "edacious", definition: "voracious devouring"},
		{word: "eddy", definition: "circular or spiral movement (e.g.. of wind)"},
		{word: "edible", definition: "fit to be eaten/not poisonous"},
		{word: "effete", definition: "infertile worn out weak"},
		{word: "efficacy", definition: "production of a desired result"},
		{word: "effluvia", definition: "outflow in a stream of particles a noxious odor or vapor"},
		{word: "effrontery", definition: "boldness impudence arrogance"},
		{word: "egress", definition: "way out exit"},
		{word: "elaborate", definition: "worked out with much care in great detail"},
		{word: "elegy", definition: "a lament a melancholy composition"},
		{word: "elicit", definition: "draw out"},
		{word: "eloquence", definition: "fluent speaking skillful use of language"},
		{word: "emaciate", definition: "make thin and weak"},
		{word: "embellish", definition: "make beautiful"},
		{word: "embezzle", definition: "use in a wrong way for one's own benefit"},
		{word: "emote", definition: "stir up excite"},
		{word: "empirical", definition: "relying on experiment"},
		{word: "encapsulate", definition: "enclose in capsule"},
		{word: "encomium", definition: "warm or glowing praise eulogy panegyric"},
		{word: "encumbrance", definition: "burden things that get on the way of"},
		{word: "endearing", definition: "making dear or liked"},
		{word: "endemic", definition: "epidemic"},
		{word: "endorse", definition: "write one's name on the back of"},
		{word: "enduring", definition: "lasting"},
		{word: "enervate", definition: "weaken deprive of strength attenuate"},
		{word: "engender", definition: "cause produce give rise to"},
		{word: "engrave", definition: "impress deeply"},
		{word: "engrossing", definition: "taken up all the time or attention writing in large or formal"},
		{word: "engulf", definition: "swallow up"},
		{word: "enigma", definition: "smth that is puzzling"},
		{word: "enmity", definition: "hatred being an enemy"},
		{word: "ensign", definition: "flag/badge"},
		{word: "entangle", definition: "put into difficulties"},
		{word: "enthral", definition: "please greatly/enslave (fig)"},
		{word: "entice", definition: "tempt or persuade"},
		{word: "entreat", definition: "ask earnestly"},
		{word: "enunciate", definition: "pronounce (words)/express a theory"},
		{word: "enzyme", definition: "catalyst"},
		{word: "epicurean", definition: "devoted to pleasure (sensuous enjoyment)"},
		{word: "epistle", definition: "letter"},
		{word: "epithet", definition: "adjective"},
		{word: "epitome", definition: "brief summary representative example a typical model"},
		{word: "equable", definition: "steady regular"},
		{word: "equanimity", definition: "calmness of temperament"},
		{word: "equilibrium", definition: "state of being balanced"},
		{word: "equipoise", definition: "equal distribution of weight equilibrium"},
		{word: "equivocal", definition: "having a double or doubtful meaning suspicious"},
		{word: "equivocate", definition: "try to deceive by equivocal language"},
		{word: "eradicate", definition: "get rid of pull up by the roots"},
		{word: "erratic", definition: "irregular in behaviour or opinion"},
		{word: "erudite", definition: "learned scholarly"},
		{word: "eschew", definition: "avoid"},
		{word: "esoteric", definition: "abstruse intended only for a small circle of"},
		{word: "espouse", definition: "marry give one's support to"},
		{word: "eulogy", definition: "formal praise panegyric"},
		{word: "euphoria", definition: "elation state of pleasant excitement"},
		{word: "euthanasia", definition: "easy and painless death"},
		{word: "evasive", definition: "tending to evade"},
		{word: "evince", definition: "to show clearly to indicate"},
		{word: "evoke", definition: "call up bring out"},
		{word: "excoriation", definition: "severe criticism"},
		{word: "exculpate", definition: "to clear from a charge of guilt"},
		{word: "exhaustive", definition: "complete thorough"},
		{word: "exigency", definition: "emergency an urgent situation"},
		{word: "exoneration", definition: "set smb clear free (e.g.. from blame)"},
		{word: "exorbitant", definition: "much too high or great"},
		{word: "expatiate", definition: "to roam wander freely"},
		{word: "expedient", definition: "likely to be useful for a purpose"},
		{word: "expiation", definition: "ending expiring"},
		{word: "exploit", definition: "brilliant achievement develop use selfishly"},
		{word: "expostulate", definition: "argue earnestly to dissuade correct or protest"},
		{word: "expurgate", definition: "to remove obscenity purify censor"},
		{word: "exscind", definition: "to cut out cut away"},
		{word: "extant", definition: "still in existence"},
		{word: "extempore", definition: "without previous thought or preparation"},
		{word: "extenuate", definition: "reduce the strength of lessen seriousness partially excuse"},
		{word: "extinct", definition: "no longer active"},
		{word: "extinguish", definition: "end the existence of/wipe or put out"},
		{word: "extirpate", definition: "to destroy exterminate cut out exscind"},
		{word: "extol", definition: "praise highly"},
		{word: "extort", definition: "obtain by threats violence"},
		{word: "extralegal", definition: "outside the law"},
		{word: "extricable", definition: "that can be freed"},
		{word: "extrovert", definition: "cheerful person"},
		{word: "exuberance", definition: "state of growing vigorously being full of life"},
		{word: "facetious", definition: "humorous funny jocular"},
		{word: "facile", definition: "easily done"},
		{word: "fallacious", definition: "based on error"},
		{word: "falter", definition: "waver/move in an uncertain manner"},
		{word: "fatuous", definition: "without sense foolish self-satisfaction"},
		{word: "fawn", definition: "young deer try to win smb's favor"},
		{word: "feckless", definition: "lacking purpose or vitality ineffective careless"},
		{word: "fecund", definition: "fertile"},
		{word: "feint", definition: "pretend"},
		{word: "felicitous", definition: "apt suitably expressed well chosen apropos"},
		{word: "felon", definition: "person guilty of murder"},
		{word: "ferment", definition: "substance become excited"},
		{word: "ferocity", definition: "savage cruelty"},
		{word: "ferret", definition: "discover by searching search"},
		{word: "fervid", definition: "showing earnest feeling"},
		{word: "fervor", definition: "warmth of feelings earnestness"},
		{word: "fetid", definition: "stinking"},
		{word: "fetter", definition: "to shackle put in chains"},
		{word: "feud", definition: "bitter quarrel over a long period of time"},
		{word: "fidelity", definition: "loyalty accuracy"},
		{word: "fidget", definition: "move restlessly make nervous"},
		{word: "figurehead", definition: "carved image on the prow of a ship"},
		{word: "finesse", definition: "delicate way of dealing with a situation"},
		{word: "finical", definition: "too fussy about food clothing etc."},
		{word: "finicky", definition: "finical"},
		{word: "fission", definition: "splitting or division (esp. of cells)"},
		{word: "fixate", definition: "stare at"},
		{word: "flak", definition: "criticism/anti-aircraft guns"},
		{word: "flamboyant", definition: "brightly colored florid"},
		{word: "flaunting", definition: "show off complacently"},
		{word: "flax", definition: "pale yellow (hair) a plant"},
		{word: "fledged", definition: "able to fly trained experienced"},
		{word: "fleet", definition: "number of ships quick-moving"},
		{word: "flinch", definition: "draw move back wince"},
		{word: "flop", definition: "fail/move/fall clumsily"},
		{word: "florid", definition: "very much ornamented naturally red (e.g.. of face)"},
		{word: "flout", definition: "reject mock to go against (as in going against tradition)"},
		{word: "fluke", definition: "lucky stroke"},
		{word: "fluster", definition: "make nervous or confused"},
		{word: "foible", definition: "defect of character (a person is wrongly proud)"},
		{word: "foil", definition: "prevent from carrying out contrast"},
		{word: "foment", definition: "put smth warm (to lessen the pain)"},
		{word: "foolproof", definition: "incapable of failure or error"},
		{word: "foppish", definition: "like a man who pays too much attention to his clothes"},
		{word: "forage", definition: "food for horses and cattle"},
		{word: "forbear", definition: "refrain from be patient ancestor"},
		{word: "forbearance", definition: "patience willingness to wait"},
		{word: "ford", definition: "shallow place in a river (to cross)"},
		{word: "forestall", definition: "prevent by taking action in advance preempt"},
		{word: "forfeit", definition: "suffer the loss of smth"},
		{word: "forge", definition: "workshop for the shaping of metal to shape metal lead"},
		{word: "forgery", definition: "counterfeit"},
		{word: "forswear", definition: "renounce disallow repudiate"},
		{word: "foster", definition: "nurture care for"},
		{word: "fracas", definition: "noisy quarrel"},
		{word: "fragile", definition: "easily injured broken or destroyed"},
		{word: "fragrant", definition: "sweet-smelling"},
		{word: "frantic", definition: "wildly excited with joy pain anxiety"},
		{word: "frenetic", definition: "frantic frenzied"},
		{word: "fret", definition: "worry irritation wear away"},
		{word: "fringe", definition: "edge ornamental border part of hair over the forehead"},
		{word: "froward", definition: "intractable not willing to yield or comply stubborn"},
		{word: "frugal", definition: "careful economical"},
		{word: "fulmination", definition: "bitter protest"},
		{word: "fulsome", definition: "disgusting offensive due to excessiveness"},
		{word: "gainsay", definition: "to deny to oppose"},
		{word: "garble", definition: "make unfair selection from facts"},
		{word: "garment", definition: "article of clothing"},
		{word: "garner", definition: "to gather and save to store up"},
		{word: "garrulity", definition: "talkativeness"},
		{word: "garrulous", definition: "too talkative"},
		{word: "gaucherie", definition: "socially awkward tactless behavior"},
		{word: "germane", definition: "relevant pertinent to"},
		{word: "gist", definition: "the point general sense"},
		{word: "glean", definition: "gather facts in small quantities"},
		{word: "glib", definition: "ready and smooth but not sincere"},
		{word: "glimmer", definition: "weak/unsteady light"},
		{word: "gloat", definition: "over look at with selfish delight"},
		{word: "glut", definition: "supply to much fill to excess"},
		{word: "gnaw", definition: "waste away bite steadily"},
		{word: "goad", definition: "smth urging a person to action"},
		{word: "gorge", definition: "eat greedily/narrow opening with a stream"},
		{word: "gossamer", definition: "soft light delicate material"},
		{word: "gouge", definition: "tool for cutting grooves in wood"},
		{word: "grandiloquent", definition: "using pompous words"},
		{word: "grave", definition: "serious requiring consideration"},
		{word: "graze", definition: "touch or scrape lightly in passing"},
		{word: "gregarious", definition: "living in societies liking the company"},
		{word: "grievous", definition: "causing grief or pain serious dire grave"},
		{word: "grovel", definition: "crawl humble oneself"},
		{word: "guile", definition: "deceit cunning"},
		{word: "gullible", definition: "easily gulled"},
		{word: "gush", definition: "burst out suddenly/talk ardently"},
		{word: "gust", definition: "outburst of feeling sudden rain wind fire etc."},
		{word: "hack", definition: "cut roughly hired horse"},
		{word: "halcyon", definition: "calm and peaceful"},
		{word: "hallow", definition: "to make holy consecrate"},
		{word: "harangue", definition: "a long passionate speech"},
		{word: "harbinger", definition: "smth or smb that foretells the coming of"},
		{word: "harrow", definition: "to distress create stress or torment"},
		{word: "haughty", definition: "arrogant conceited"},
		{word: "heed", definition: "attention/give notice to"},
		{word: "heinous", definition: "odious (of crime)"},
		{word: "heresy", definition: "belief contrary to what is generally accepted"},
		{word: "hermetic", definition: "sealed by fusion"},
		{word: "heterogeneous", definition: "made up of different kinds"},
		{word: "hew", definition: "make by hard work cut (by striking)"},
		{word: "highbrow", definition: "(person) with superior tastes"},
		{word: "hirsute", definition: "hairy shaggy"},
		{word: "hoax", definition: "mischievous trick played on smb for a joke"},
		{word: "hoi", definition: "polloi the masses the rabble"},
		{word: "hollow", definition: "not soled with hole"},
		{word: "holster", definition: "leather case for a pistol"},
		{word: "homiletics", definition: "act of preaching"},
		{word: "hone", definition: "stone used for sharpening tools"},
		{word: "hoodwink", definition: "trick mislead"},
		{word: "hospitable", definition: "liking to give hospitality"},
		{word: "hubris", definition: "arrogant pride"},
		{word: "hush", definition: "make or become silent"},
		{word: "husk", definition: "worthless outside part of anything"},
		{word: "hypocrisy", definition: "falsely making oneself appear to be good"}
	]
};

module.exports = notebook; 